# Generated by Django 4.2.7 on 2023-11-30 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promiedos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='team_league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promiedos.liga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipo_jugador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promiedos.equipo'),
        ),
    ]
