# Generated by Django 4.2.7 on 2023-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promiedos', '0002_equipo_team_league_jugador_equipo_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='team_points',
            field=models.IntegerField(default=0),
        ),
    ]
