# Generated by Django 4.2.7 on 2023-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promiedos', '0004_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
