# Generated by Django 4.2.2 on 2023-12-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promiedos', '0005_partido_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo_jugador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='promiedos.equipo'),
        ),
    ]
