# Generated by Django 4.2.2 on 2023-12-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promiedos', '0006_alter_jugador_equipo_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='role',
            field=models.CharField(choices=[(1, 'ARQ'), (2, 'DEF'), (3, 'MD'), (4, 'DC')], max_length=3),
        ),
    ]
