# Generated by Django 4.2.2 on 2023-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promiedos', '0007_alter_jugador_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='role',
            field=models.CharField(choices=[('ARQ', 'ARQ'), ('DEF', 'DEF'), ('MD', 'MD'), ('DC', 'DC')], max_length=3),
        ),
    ]
