# Generated by Django 4.2.7 on 2023-12-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promiedos', '0008_alter_jugador_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='role',
            field=models.CharField(choices=[('ARQ', 1), ('DEF', 2), ('MD', 3), ('DC', 4)], max_length=3),
        ),
    ]
