# Generated by Django 5.0 on 2023-12-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promiedos', '0009_alter_jugador_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='team_league',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='team_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='player_name',
            new_name='name',
        ),
    ]
